<?php

/**
 * Implementation of hook_help().
 */
function clone_help($section) {
  switch ($section) {
    case 'admin/help#clone':
      $output = '<p>'. t('The clone module allows users to make a copy of an existing node and then edit that copy. The authorship is set to the current user, the menu and url aliases are reset, and the words "Clone of" are inserted into the title to remind you that you are not editing the original node.') .'</p>';
      $output .= '<p>'. t('Users with the "clone node" permission can utilize this functionality. A new tab will appear on node pages with the word "Clone".') .'</p>';
      return $output;
  }
}

/**
* Implementation of hook_perm().
*/
function clone_perm() {
  return array('clone node');
}

/**
 * Implementation of hook_menu().
 */
function clone_menu($may_cache) {
  $items = array();

  if ($may_cache) {  
    $items[] = array(
       'path' => 'admin/settings/clone',
       'title' => t('Clone module'),
       'description' => t('Allows users to clone (copy then edit) an existing node.'),
       'callback' => 'drupal_get_form',
       'callback arguments' => 'clone_settings',
       'access' => user_access('administer site configuration'), 
      );
  }
  else { 
    if (arg(0) == 'node' && is_numeric(arg(1))){
       $node = node_load(arg(1));
       if ($node->nid) {
         $access = (user_access('clone node') && filter_access($node->format) && node_access('create',$node->type));
         $items[] = array(
           'path' => 'node/'. $node->nid.'/clone', 
           'title' => t('Clone'),
           'callback' => 'clone_node',
           'callback arguments' => $node->nid,
           'access' => $access,
           'type' => MENU_LOCAL_TASK, 'weight' => 5,); 
       }
    }
  }

  return $items;
}

/**
* menu callback to configure module settings.
*/
function clone_settings() {

  $form['heading'] = array(
    '#value' => '<b>'.t('Configuration options for the clone module:').'</b>',
  );

  $form['publishing'] = array(
    '#type' => 'fieldset',
    '#title' => '<b>'.t('Should the publishing options ( e.g. published, promoted, etc) be reset to the defaults?').'</b>',
  );
  
  foreach (node_get_types() as $type_obj) {
    $form['publishing']['clone_reset_'. $type_obj->type] = array(
      '#type' => 'checkbox',
      '#title' => t('@s: reset publishing options when cloned', array('@s' => $type_obj->name)),
      '#default_value' => variable_get('clone_reset_'. $type_obj->type, FALSE),
    );    
  }

  return system_settings_form($form);
}

/**
 * Implementation of hook_mode_type().
 */
function clone_node_type($op, $type_obj) {

  switch ($op){
    case 'delete':
      variable_del('clone_reset_'. $type_obj->type);
      break;
    case 'update':
      if (!empty($type_obj->old_type) && $type_obj->old_type != $type_obj->type) {
        if (variable_get('clone_reset_'. $type_obj->old_type, FALSE)) {
          variable_del('clone_reset_'. $type_obj->old_type);
          variable_set('clone_reset_'. $type_obj->type, TRUE);
        }
      }
      break;
  }
}

/**
 *  Clones a node - prepopulate a node editing form
 */
function clone_node($nid)
{
  if (is_numeric($nid)) {
    global $user;
    
    $node = node_load($nid);
    if (isset($node->nid)) {
      
      $node->nid = NULL;
      $node->name = $user->name;
      $node->uid = $user->uid;
      $node->created = NULL;   
      $node->menu = NULL;
      $node->path = NULL;
      $node->files = array();
      $node->title = t('Clone of !title', array('!title' => $node->title));
      drupal_set_title(check_plain($node->title));
      
      if (variable_get('clone_reset_'. $node->type, FALSE)) {
        $node_options = variable_get('node_options_'. $node->type, array('status', 'promote'));
        // fill in the default values
        foreach (array('status', 'moderate', 'promote', 'sticky', 'revision') as $key) {
          $node->$key = in_array($key, $node_options);
        } 
      }
      if (empty($_POST['op'])) {
        drupal_set_message('This clone will not be saved to the database until you submit.');
      }
      return  drupal_get_form($node->type .'_node_form', $node); 
    }
  }
}

